#!/bin/sh
#Primary screen in DP1
xrandr --output DisplayPort-1 -s 2560x1440 --rate 240 --primary 
#Flipped screen in DP2
xrandr --output DisplayPort-2 --left-of DisplayPort-1 --mode 1920x1080 --rate 144 --rotate left 