#!/bin/sh

options="poweroff\nreboot\nsuspend\nhibernate"

choice=$(echo -e $options | dmenu -i -fn 'JetBrains Mono:size=13' -nb '#000000' -nf '#ffffff' -sb '#000000' -sf '#ffffff')

case $choice in 
    poweroff)
        systemctl poweroff
        ;;
    reboot)
        systemctl reboot
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    logout)
        sudo pkill Xorg
        ;;
esac