#!/bin/sh

options="poweroff\nreboot\nsuspend\nhibernate\nlogout"

echo -e $options | dmenu -i -fn 'JetBrains Mono:size=13' -nb '#000000' -nf '#ffffff' -sb '#000000' -sf '#ffffff' | xargs -I{} sh -c "systemctl {}"